services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-rpc
    pull_policy: never
    container_name: myrpc
    restart: always
    ports:
      - "6363:6363"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - microservice-network
  db:
    image: postgres:16-alpine3.20
    container_name: mydata
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin345
      POSTGRES_DB: example
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init/schema/schema.sql:/docker-entrypoint-initdb.d/spmi.sql
    networks:
      - microservice-network

volumes:
  postgres-data:
networks:
  microservice-network:
    driver: bridge
