services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app
    pull_policy: never
    container_name: myapp
    restart: always
    ports:
      - "7373:7373"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db
    networks:
      - kalveir-network
  db:
    image: postgres:16-alpine3.20
    container_name: mydb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperPassword123
      POSTGRES_DB: api_store
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kalveir-network

volumes:
  postgres-data:
networks:
  kalveir-network:
    driver: bridge
